/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchLibraryIndexRouteImport } from './routes/research-library.index'
import { Route as ResearchLibrarySlugRouteImport } from './routes/research-library.$slug'

const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchLibraryIndexRoute = ResearchLibraryIndexRouteImport.update({
  id: '/research-library/',
  path: '/research-library/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchLibrarySlugRoute = ResearchLibrarySlugRouteImport.update({
  id: '/research-library/$slug',
  path: '/research-library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/research-library/$slug': typeof ResearchLibrarySlugRoute
  '/research-library/': typeof ResearchLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/research-library/$slug': typeof ResearchLibrarySlugRoute
  '/research-library': typeof ResearchLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/research-library/$slug': typeof ResearchLibrarySlugRoute
  '/research-library/': typeof ResearchLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/coming-soon' | '/research-library/$slug' | '/research-library/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coming-soon' | '/research-library/$slug' | '/research-library'
  id:
    | '__root__'
    | '/'
    | '/coming-soon'
    | '/research-library/$slug'
    | '/research-library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ResearchLibrarySlugRoute: typeof ResearchLibrarySlugRoute
  ResearchLibraryIndexRoute: typeof ResearchLibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-library/': {
      id: '/research-library/'
      path: '/research-library'
      fullPath: '/research-library/'
      preLoaderRoute: typeof ResearchLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-library/$slug': {
      id: '/research-library/$slug'
      path: '/research-library/$slug'
      fullPath: '/research-library/$slug'
      preLoaderRoute: typeof ResearchLibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComingSoonRoute: ComingSoonRoute,
  ResearchLibrarySlugRoute: ResearchLibrarySlugRoute,
  ResearchLibraryIndexRoute: ResearchLibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
